language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
env:
  - NODE_VERSION=12.6.0

install:
  - nvm install $NODE_VERSION

script:
  - nvm use $NODE_VERSION
  - dir
  - cd typescryptimplementation
  - npm install grunt-cli --save-dev
  - npm install grunt@0.4.5 --save-dev
  - npm install grunt-ts --save-dev
  - npm install grunt-contrib-clean --save-dev
  - npm install grunt-contrib-uglify --save-dev
  - npm install grunt-contrib-yuidoc --save-dev
  - npm install grunt-mocha-cli --save-dev
  - npm install grunt-mocha-test --save-dev
  - npm install typescript --save-dev
  - npm install chai --save-dev
  - npm install mocha --save-dev
  - npm install amd-loader --save-dev
  - npm install @types/chai --save-dev
  - npm install @types/mocha --save-dev
  - dir
  - npm install
  - dir
  - cd ..
  - mvn test -B
